### PR TITLE
Remove duplicate include of <sys/mount.h>

### PR DESCRIPTION
**Pull request by kraj**
<sys/mount.h> is already included by lapi/mount.h.

This fixes build with glibc 2.36+

Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by pevik** [comment]
Well statx09.c does not include `lapi/mount.h`, therefore build fails: `statx09.c:119:7: error: implicit declaration of function 'mount' [-Werror=implicit-function-declaration]`.
Also we prefer patches to our mailing list: https://lists.linux.it/listinfo/ltp (https://github.com/linux-test-project/ltp#developers-corner)
