### ISSUE TITLE
ptrace tests fail to build with glibc-2.18

### ISSUE THREAD

**Issue by hwoarang** [linux-test-project/ltp#6]
sys/ptrace.h from glibc-2.18 defines ptrace_peeksiginfo_args which is also defined in linux/ptrace.h

This breaks the build on the ptrace tests:

gcc -g -O2 -g -O2 -fno-strict-aliasing -pipe -Wall -D_FORTIFY_SOURCE=2 -I/home/test/src/toolchain/ltp/testcases/kernel/include -I../../../../include -I../../../../include   -L../../../../lib  ptrace04.c   -lltp -o ptrace04
In file included from ptrace.h:22:0,
                 from ptrace04.c:18:
/usr/include/linux/ptrace.h:58:8: error: redefinition of 'struct ptrace_peeksiginfo_args'
 struct ptrace_peeksiginfo_args {
        ^
In file included from ptrace.h:9:0,
                 from ptrace04.c:18:
/usr/include/sys/ptrace.h:191:8: note: originally defined here
 struct ptrace_peeksiginfo_args
