### ISSUE TITLE
make fails when cross-compiling for arm

### ISSUE THREAD

**Issue by alexchu-cpe** [linux-test-project/ltp#555]
Tested using this line.
`make -j16 distclean; make -j16 autotools; ./configure --host=arm-linux; make;`

Failed with this message (also see attached log):
```
arm-linux-gcc -g -O2 -g -O2 -fno-strict-aliasing -pipe -Wall -W -Wold-style-definition -D_FORTIFY_SOURCE=2 -I../../../../include -I../../../../include -I../../../../include/old/   -L../../../../lib  copy_file_range03.c   -lltp -o copy_file_range03
In file included from copy_file_range.h:15:0,
                 from copy_file_range02.c:37:
../../../../include/lapi/fs.h:44:51: error: 'PAGE_SHIFT' undeclared here (not in a function)
  #define MAX_LFS_FILESIZE   ((loff_t)ULONG_MAX << PAGE_SHIFT)
                                                   ^
copy_file_range.h:33:19: note: in expansion of macro 'MAX_LFS_FILESIZE'
 #define MAX_LEN   MAX_LFS_FILESIZE
                   ^~~~~~~~~~~~~~~~
copy_file_range.h:35:20: note: in expansion of macro 'MAX_LEN'
 #define MAX_OFF   (MAX_LEN - MIN_OFF)
                    ^~~~~~~
copy_file_range02.c:75:35: note: in expansion of macro 'MAX_OFF'
  {&fd_copy,      0,   EOVERFLOW,  MAX_OFF, ULLONG_MAX},
                                   ^~~~~~~
make[4]: *** [copy_file_range02] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory `/local/public/users/ac945939/kernel_auto/ltp/ltp_source/testcases/kernel/syscalls/copy_file_range'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/local/public/users/ac945939/kernel_auto/ltp/ltp_source/testcases/kernel/syscalls'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/local/public/users/ac945939/kernel_auto/ltp/ltp_source/testcases/kernel'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/local/public/users/ac945939/kernel_auto/ltp/ltp_source/testcases'
make: *** [testcases-all] Error 2
```

I git bisect'ed to this commit:
```
bc514b22452a96ec7fc12e500ad8d0083ae761d9 is the first bad commit
commit bc514b22452a96ec7fc12e500ad8d0083ae761d9
Author: Yang Xu <xuyang2018.jy@cn.fujitsu.com>
Date:   Wed Jul 31 18:40:29 2019 +0800

    syscalls/copy_file_range02: increase coverage and remove EXDEV test

    Since kernel commit 96e6e8f4a68d ("vfs: add missing checks to copy_file_range")
    we should add swapfile, immutable file, bounds tests in LTP.
    Also, add block, char, pipe dev tests and remove EXDEV test (the cross-device
    constraint has been relaxed since kernel commit 5dae222a5ff0 ("vfs:
    allow copy_file_range to copy across devices").

    This follows tests 553, 554, 564, 565 from xfstests [1].

    [1] https://git.kernel.org/pub/scm/fs/xfs/xfstests-dev.git/tree/tests/generic/{553,554,564,565}

    Signed-off-by: Yang Xu <xuyang2018.jy@cn.fujitsu.com>
    Reviewed-by: Amir Goldstein <amir73il@gmail.com>
    Acked-by: Cyril Hrubis <chrubis@suse.cz>
    Signed-off-by: Petr Vorel <pvorel@suse.cz>

:040000 040000 3c7ade7f9f1b675016bc1e8f0bda25ad20bce7d8 ef31b29bf3077abf94585cfe81f21f96de34f78f M      include
:040000 040000 bf85b5ff3be8fea0c7c906557c9b193711bb3a23 30f60c53bbac17a6c83b108c87aa0453ae64b89c M      testcases
[arm-make.txt](https://github.com/linux-test-project/ltp/files/3488377/arm-make.txt)

```

**Comment by alexchu-cpe** [comment]
I need to do the bisect again. Will update on Monday.

**Comment by pevik** [comment]
Hm, that's strange. `PAGE_SHIFT` is defined in `<sys/user.h>` for glibc, which is included in `lapi/fs.h`.

We do have aarch64 builds in CI [1] and it builds [2], but arm (assume 32bit) might be based on some old version. Can you please be more specific about used toolchain (`arm-linux-gcc -v`) and libc?

[1] https://github.com/linux-test-project/ltp/blob/master/.travis.yml#L19
[2] https://github.com/linux-test-project/ltp/commits/master

**Comment by alexchu-cpe** [comment]
Was able to reproduce it with the standard toolchain as well:
https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-a/downloads

> ac945939@stbirv-sqa-1 Tue 08/13 03:17:18:/local/public/users/ac945939/kernel_auto/ltp/ltp_source$ arm-linux-gnueabihf-gcc -v
> Using built-in specs.
> COLLECT_GCC=arm-linux-gnueabihf-gcc
> COLLECT_LTO_WRAPPER=/local/public/users/ac945939/kernel_auto/temp/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/../libexec/gcc/arm-linux-gnueabihf/8.3.0/lto-wrapper
> Target: arm-linux-gnueabihf
> Configured with: /tmp/dgboter/bbs/rhev-vm8--rhe6x86_64/buildbot/rhe6x86_64--arm-linux-gnueabihf/build/src/gcc/configure --target=arm-linux-gnueabihf --prefix= --with-sysroot=/arm-linux-gnueabihf/libc --with-build-sysroot=/tmp/dgboter/bbs/rhev-vm8--rhe6x86_64/buildbot/rhe6x86_64--arm-linux-gnueabihf/build/build-arm-linux-gnueabihf/install//arm-linux-gnueabihf/libc --with-bugurl=https://bugs.linaro.org/ --enable-gnu-indirect-function --enable-shared --disable-libssp --disable-libmudflap --enable-checking=release --enable-languages=c,c++,fortran --with-gmp=/tmp/dgboter/bbs/rhev-vm8--rhe6x86_64/buildbot/rhe6x86_64--arm-linux-gnueabihf/build/build-arm-linux-gnueabihf/host-tools --with-mpfr=/tmp/dgboter/bbs/rhev-vm8--rhe6x86_64/buildbot/rhe6x86_64--arm-linux-gnueabihf/build/build-arm-linux-gnueabihf/host-tools --with-mpc=/tmp/dgboter/bbs/rhev-vm8--rhe6x86_64/buildbot/rhe6x86_64--arm-linux-gnueabihf/build/build-arm-linux-gnueabihf/host-tools --with-isl=/tmp/dgboter/bbs/rhev-vm8--rhe6x86_64/buildbot/rhe6x86_64--arm-linux-gnueabihf/build/build-arm-linux-gnueabihf/host-tools --with-arch=armv7-a --with-fpu=neon --with-float=hard --with-arch=armv7-a --with-pkgversion='GNU Toolchain for the A-profile Architecture 8.3-2019.03 (arm-rel-8.36)'
> Thread model: posix
> gcc version 8.3.0 (GNU Toolchain for the A-profile Architecture 8.3-2019.03 (arm-rel-8.36))

> ac945939@stbirv-sqa-1 Tue 08/13 03:38:25:/local/public/users/ac945939/kernel_auto/ltp/ltp_source$ arm-linux-gnueabihf-ld --version
> GNU ld (GNU Toolchain for the A-profile Architecture 8.3-2019.03 (arm-rel-8.36)) 2.32.0.20190321
> Copyright (C) 2019 Free Software Foundation, Inc.
> This program is free software; you may redistribute it under the terms of
> the GNU General Public License version 3 or (at your option) a later version.
> This program has absolutely no warranty.

**Comment by pevik** [comment]
Thanks for info, I'll have a look.

**Comment by pevik** [comment]
Confirmed. `PAGE_SHIFT` isn't defined on some libc. (BTW which do you use and which libc does arm-linux-gnueabihf use?)

@metan-ucw any idea, how to workaround it?
It comes from `#define MAX_LFS_FILESIZE   ((loff_t)ULONG_MAX << PAGE_SHIFT)`, which originated from https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0cc3b0ec23ce4c69e1e890ed2b8d2fa932b14aad from v4.13-rc7.
There is in glibc and uclibc `PAGE_SHIFT` defined for each arch (default is 12) and then `PAGE_SIZE` is defined as `(1UL << PAGE_SHIFT)`.

Recommendation is to use `getpagesize()` (or `sysconf(_SC_PAGESIZE)`) in userspace, but that does not expect that we really need `PAGE_SHIFT`.
Or should we check for `PAGE_SHIFT` in compile time?

**Comment by metan-ucw** [comment]
@pevik I guess that the safest option would be using the getpagesize() and figure out the value at runtime.

**Comment by pevik** [comment]
@metan-ucw but the problem is how to get `PAGE_SHIFT` from `PAGE_SIZE`.

**Comment by metan-ucw** [comment]
@pevik The ULONG_MAX << PAGE_SHIFT effectively zeroes lower bits it should be equal to (ULONG_MAX & ~(getpagesize() - 1).

**Comment by metan-ucw** [comment]
@pevik scratch, that we also cast the ULONG_MAX to loff_t (i.e. long long), then we have to really shift with something as:

```
loff_t get_max(void)
{
        long page_size = getpagesize();
        loff_t ret = ULONG_MAX;

        while (page_size>>=1)
                ret<<=1;

        return ret;
}
```

**Comment by pevik** [comment]
```
#define TST_GET_MAX_32BIT \
({ \
        long page_size = getpagesize(); \
        loff_t ret = ULONG_MAX; \
 \
        while (page_size >>= 1) \
                ret <<= 1; \
 \
        ret; \
})
```
Hm, I defined macro but that's not working for copy_file_range02.c, where it's used in `static struct tcase` outside of the function. I get 
`../../../../include/lapi/fs.h:43:1: error: braced-group within expression allowed only inside a function`.

**Comment by metan-ucw** [comment]
Well yes, the you cannot initialize constant by a function call, hence we should rather define this as a function and then call it from the test setup...

**Comment by alexchu-cpe** [comment]
"(BTW which do you use and which libc does arm-linux-gnueabihf use?)"
Sorry, forgot about that. I use both toolchains and they both use glibc.

**Comment by pevik** [comment]
@alexchu-cpe FYI I sent a patch to ML
https://patchwork.ozlabs.org/patch/1147475/

I added your `Reported-by: alexchu-cpe`, if you give me your email, I'll fill it there (standard procedure). Thanks a lot for reporting.

**Comment by alexchu-cpe** [comment]
Hi Petr,
My email is alexchu.cpe@gmail.com.
Also, I just tested your patch and it indeed builds fine with both toolchains.

Thanks!
-Alex
